version: '3.7'
services:
  api-csv-charge:
    container_name: api-csv-charge
    restart: on-failure
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: yarn start:dev
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local